# Generated by Django 5.0.3 on 2026-03-17 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        ("devices", "0001_initial"),
        ("firearms", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="firearm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="firearms.firearm",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["organization", "-created_at"], name="alerts_organiz_621e9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["organization", "resolved_at"], name="alerts_organiz_8d48b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["device", "-created_at"], name="alerts_device__957e7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["dedup_key", "resolved_at"], name="alerts_dedup_k_c00477_idx"
            ),
        ),
    ]
