# Generated by Django 5.0.3 on 2026-03-17 20:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("firearms", "0001_initial"),
        ("organizations", "0001_initial"),
        ("telemetry", "0003_brin_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "area",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("color", models.CharField(default="#FF5733", max_length=7)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_geofences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofences",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "geofences",
            },
        ),
        migrations.CreateModel(
            name="GeofenceAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.CharField(
                        choices=[
                            ("stay_inside", "Must Stay Inside"),
                            ("stay_outside", "Must Stay Outside"),
                        ],
                        default="stay_inside",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firearm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_assignments",
                        to="firearms.firearm",
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="geofencing.geofence",
                    ),
                ),
            ],
            options={
                "db_table": "geofence_assignments",
            },
        ),
        migrations.CreateModel(
            name="GeofenceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("enter", "Entered"), ("exit", "Exited")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("alert_generated", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="geofencing.geofenceassignment",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_events",
                        to="telemetry.location",
                    ),
                ),
            ],
            options={
                "db_table": "geofence_events",
            },
        ),
        migrations.AddIndex(
            model_name="geofence",
            index=models.Index(
                fields=["organization", "is_active"],
                name="geofences_organiz_8fceea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geofenceassignment",
            index=models.Index(
                fields=["firearm", "is_active"], name="geofence_as_firearm_433c13_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="geofenceassignment",
            unique_together={("geofence", "firearm")},
        ),
        migrations.AddIndex(
            model_name="geofenceevent",
            index=models.Index(
                fields=["assignment", "-timestamp"],
                name="geofence_ev_assignm_a74c92_idx",
            ),
        ),
    ]
