# Generated by Django 6.0.3 on 2026-03-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geofencing', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofenceevent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='telemetry.location'),
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['organization', 'is_active'], name='geofences_organiz_8fceea_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceassignment',
            index=models.Index(fields=['firearm', 'is_active'], name='geofence_as_firearm_433c13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geofenceassignment',
            unique_together={('geofence', 'firearm')},
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['assignment', '-timestamp'], name='geofence_ev_assignm_a74c92_idx'),
        ),
    ]
