# Generated by Django 5.0.3 on 2026-03-17 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("firearms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField()),
                ("battery_level", models.SmallIntegerField()),
                ("signal_strength", models.SmallIntegerField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("is_charging", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "device_health",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("api_key_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("low_battery", "Low Battery"),
                            ("tampered", "Tampered"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="offline",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("last_battery", models.SmallIntegerField(blank=True, null=True)),
                ("last_latitude", models.FloatField(blank=True, null=True)),
                ("last_longitude", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provisioned_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firearm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="firearms.firearm",
                    ),
                ),
            ],
            options={
                "db_table": "devices",
            },
        ),
    ]
