# Generated by Django 5.0.3 on 2026-03-17 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("firmware", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="firmware_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="firmware.firmwareversion",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="devicehealth",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_records",
                to="devices.device",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["organization", "status"], name="devices_organiz_a5e314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["uid"], name="devices_uid_e8741a_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["last_seen"], name="devices_last_se_cc30d3_idx"),
        ),
        migrations.AddIndex(
            model_name="devicehealth",
            index=models.Index(
                fields=["device", "timestamp"], name="device_heal_device__7e77bb_idx"
            ),
        ),
    ]
