# Generated by Django 5.0.3 on 2026-03-17 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=500)),
                ("status_code", models.SmallIntegerField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("body", models.JSONField(blank=True, default=dict)),
                ("elapsed_ms", models.IntegerField(default=0)),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_logs_timesta_e93820_idx"
                    ),
                    models.Index(
                        fields=["user_id", "-timestamp"],
                        name="audit_logs_user_id_e11c73_idx",
                    ),
                    models.Index(
                        fields=["organization_id", "-timestamp"],
                        name="audit_logs_organiz_ab3135_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_logs_object__457405_idx",
                    ),
                ],
            },
        ),
    ]
