# Generated by Django 5.0.3 on 2026-03-17 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirearmCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firearm_categories",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "firearm_categories",
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="Firearm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("serial_number", models.CharField(max_length=100)),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("calibre", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("lost", "Lost"),
                            ("stolen", "Stolen"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="firearms/"),
                ),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_firearms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firearms",
                        to="organizations.organization",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firearms",
                        to="firearms.firearmcategory",
                    ),
                ),
            ],
            options={
                "db_table": "firearms",
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="firearms_organiz_c241a7_idx",
                    ),
                    models.Index(
                        fields=["serial_number"], name="firearms_serial__5a505b_idx"
                    ),
                ],
                "unique_together": {("organization", "serial_number")},
            },
        ),
    ]
